### ISSUE TITLE
[DarkFiberMines] add to Insight API

### ISSUE THREAD

**Issue by DarkFiberMines** [bitcoinz-dev-tools/insight-api-btcz#15]
**Your Pool Name Here (also in tittle)**
DarkFiberMines

**Needed Informations**
We need your pool name, your pool URL and the HEX string of both.

DarkFiberMines https://btcz.darkfibermines.com
4254437A417070506F6F6C2068747470733A2F2F6D696E652E6274637A2E617070

**Additional context**
Add any other context about the request here.

**Comment by MarcelusCH** [comment]
Hey, 
Thanks for your request ! 
Just as Discord's disscution, please update your HEX string with your own info. You can using any ASCI to HEX online converter. 
I will push the update ASAP after this change. 
Also not forget to update the HEX string in your pool conf file!

**Comment by DarkFiberMines** [comment]
Here is my updated hex string! A bit longer than yours? 4461726b46696265724d696e65732068747470733a2f2f6274637a2e6461726b66696265726d696e65732e636f6d

I have updated my pool with that string.

Regards,
