### ISSUE TITLE
2Mars add to Insight API

### ISSUE THREAD

**Issue by Peter197903** [bitcoinz-dev-tools/insight-api-btcz#17]
Your Pool Name Here (also in tittle)
2Mars

Needed Informations
We need your pool name, your pool URL and the HEX string of both.

2Mars https://btcz.2mars.biz
324d617273202d2068747470733a2f2f6274637a2e326d6172732e62697a 

Additional context
Add any other context about the request here.

**Comment by cryptorex** [comment]
Test issue
